dist: trusty
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-11/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: VYFmLzqIaYHHD2pepBN0XtOWL59UvjrXGSiLNgJfO84rE9qJgsmluDs4yfDXacVU2eLWO9P+S6HdVlG87ue0Hnybt9yHqAFpThPxpYD2VPoJoF8keK/wg6Xa1W9LAW41dgRbcqIqMDMbXMuHm6T/Yv3F39lM+bfMb76tAoYD3kxlxL/lUCc9q86W73LUSKacu4NeH0+fpXT7c3yI0abVk9oSgy/LDHFxZaWpoH8vRRQcj8S0BCOyI5mHUq/KU/DL2VIqV3uMnbh5CwWqGUO2DczAnhr3r2IB1gNxCQ6uDK9KEHWnKUzeQoF3pSxx0SIkwGcqMUotyKX7OWFQDNeYY4PNI+EuM+s53qJSDI35lMK0BDhOeopTRftc4fSIyZr/5Rt5Rg7lv89BXmwgxj0kAadb0HKDK7R2MQ6arCL7cHOb9S3aY92UDsJ6/7mC9kQUDQwah9t1dLJ8Lvqyr72PU868qVOfiNzb7vJc+e+pjwT4fIbFNACQqZzjsScFOnsSGctVgQv6a7pV/n1HWNpF+XAgBJ+fUYhk6bVGQxpVfsaeatv1Gbo450rPWHeMzxbZ3icKMuH8ExR1R3IrFfHuh6HznLA91FiWqmbvmPQVBWOXCwUNMCNOVQ7ZYQxL87Vq91EuKVSgTfvvti3pJt+guHjtAu0V4x0Vqf+PEbU+SRc=
    on_failure: always
    on_success: always
