dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-11/run.sh |
  bash
notifications:
  slack:
    secure: JbdaOdqyYzwVB0B/uFWdOijNYQjbrP4Hr2M8xjNhyXCBExzHkgNKnA1LPF3VIGi+2qlMmDfW3z7tA7bsVm1uHVC4fMDO1fAls7R2g7kVur6qRLRll44BvXiJ6+sY5tvB26Py3gu/VjesgzlOWy5z7Td0n+izrpjJeV+TP+hETmEhxYTqiDojmlJdqAP+lsAs0O4vfv03QYpyWDyk6VowWlaM+63gC9Nag3Vs9N5cnXUMzpP3crhS+BVmaGxTHxF6lMc3dhOZZ82xZnaWA3GqM9SghmqPuB/mjR0Cl2gZUjs6JpdeOZ0kIIw8nC4R60aT5/Z7Q+8YNeEP4RLF0K4XF87HMGQZt7C1uoL3YbEXYgbz9EpZD+CYREOxkELpr7NdUxeim0aX1CgO16aTK31kckTPgaVsbJrZ+w2t9bjcQqgT71Gx063223hpmed9oZUEi3oAQb6h5FpttXM9e3S48LYDhp3ppAlDL/NtY2dggmK1arQom5jgVwVUN6Acdq9uvU+AoP0LHQWsjKNQJJgnn99LzE5czF1mKeIsO5Odmx4Co6y5mPE907qO1F4/ApDbO5Qq8TmCDYWszE200SI1x5gqvlP4QOQkL/5jLBc79mDd4TGxOJgpkRJhLNgKt0dWrrRqTcRnKgGDYpYltFQ3zIWVMcQr9oHPTrzi4GHDheQ=
